version: "3.9"
services:
  web:
    build: ./web
    ports:
      - "3000:3000"
    volumes:
      - ./web/src:/src

  server:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server/api:/app/api
      - ./server/app.py:/app/app.py
    environment:
      - POSTGRES_URL=postgresql+psycopg2://postgres:postgres@postgres:5432/personal_website
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - APP_DB_NAME=personal_website
    volumes: 
      - ./postgres:/docker-entrypoint-initdb.d/